/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinamore.view;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinamore.controller.ManageChefController;
import lk.ijse.dinamore.controller.ManageOrderController;
import lk.ijse.dinamore.dto.OrderDTO;
import lk.ijse.dinamore.observer.Observer;

/**
 *
 * @author Ravindu
 */
public class ReceptionForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Chef_view_controller
     */
    private DefaultTableModel dtm;

    public ReceptionForm() throws RemoteException, Exception {
        initComponents();
        loadAllCustomers();
        loadAllReception();
        getDateAndTime();
        getClock();
        UnicastRemoteObject.exportObject(this, 0);
        ManageOrderController.getSubeject().registerObserver(this);
    }

    int avqty;
    String cstatus;

    private void getDateAndTime() {
        Date date = new Date();
        SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd");
        String new_DATE = simpledateformat.format(date);
        lbldate.setText(new_DATE);

    }

    private void loadAllCustomers() {
        dtm = (DefaultTableModel) tblorder.getModel();
        dtm.setRowCount(0);
        try {
            List<OrderDTO> orders = ManageOrderController.getAllCustomers();
            if (orders == null) {
                return;
            }

            for (OrderDTO orderDTO : orders) {
                Object[] rowData = {
                    orderDTO.getOrderId(),
                    orderDTO.getCustName(),
                    orderDTO.getTpNo(),
                    orderDTO.getTime(),
                    orderDTO.getQty(),
                    orderDTO.getStatus()
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getClock() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss aa");
                    String currentTime = dateFormat.format(curDate);

                    lbltime.setText(currentTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(ReceptionForm.this, "Database Error...");
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbrecep = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtoid = new javax.swing.JTextField();
        txtcustname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblorder = new javax.swing.JTable();
        btnplace_order = new javax.swing.JButton();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jsqty = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reception");
        jLabel1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rec. Name");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/dinamore/images/icons8_Reception_100px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbrecep, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbrecep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Order ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 30));
        jPanel2.add(txtoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 190, 30));
        jPanel2.add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 260, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TP");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 20, 30));
        jPanel2.add(txttp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("QTY");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 30));

        tblorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer Name", "TP", "Time", "QTY", "Status"
            }
        ));
        tblorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblorderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblorder);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 740, 170));

        btnplace_order.setBackground(new java.awt.Color(134, 115, 167));
        btnplace_order.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnplace_order.setText("Send To Kitchen");
        btnplace_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplace_orderActionPerformed(evt);
            }
        });
        jPanel2.add(btnplace_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, 40));

        lbltime.setBackground(new java.awt.Color(102, 102, 102));
        lbltime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltime.setForeground(new java.awt.Color(102, 102, 102));
        lbltime.setText("Time");
        jPanel2.add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        lbldate.setBackground(new java.awt.Color(102, 102, 102));
        lbldate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldate.setForeground(new java.awt.Color(102, 102, 102));
        lbldate.setText("Date");
        jPanel2.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));
        jPanel2.add(jsqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 30));

        jButton1.setBackground(new java.awt.Color(82, 176, 169));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Update Qty");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 190, 40));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Log Out");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplace_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplace_orderActionPerformed
        try {
            String ststus = "On Going";

            int qty = Integer.parseInt(jsqty.getValue() + "");

            OrderDTO orderDTO = new OrderDTO(
                    txtoid.getText(),
//                    txtrid.getText(),
                    cmbrecep.getSelectedItem().toString(),
                    lbldate.getText(),
                    lbltime.getText(),
                    txtcustname.getText(),
                    txttp.getText(),
                    qty,
                    ststus
            );
            boolean addorder = ManageOrderController.placeOrder(orderDTO);
            if (addorder) {
                JOptionPane.showMessageDialog(this, "Order has been Added Successfully");
                loadAllCustomers();
//                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Place Order");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }     }//GEN-LAST:event_btnplace_orderActionPerformed

    private void tblorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblorderMouseClicked
        int selectedRow = tblorder.getSelectedRow();
        String oid = dtm.getValueAt(selectedRow, 0).toString();
        String cusname = dtm.getValueAt(selectedRow, 1).toString();
        String tp = dtm.getValueAt(selectedRow, 2).toString();
        String tqty = dtm.getValueAt(selectedRow, 4).toString();
        cstatus = dtm.getValueAt(selectedRow, 5).toString();

        avqty = Integer.parseInt(tqty);

        txtoid.setText(oid);
        txtcustname.setText(cusname);
        txttp.setText(tp);
//        jsqty.setValue(qty);
    }//GEN-LAST:event_tblorderMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int qty = Integer.parseInt(jsqty.getValue() + "");
        String uoc = cstatus;
        System.out.println(cstatus);

        if (avqty < qty && "On Going".equals(uoc)) {
            try {
                String ststus = "On Going";
                OrderDTO orderDTO = new OrderDTO(
                        txtoid.getText(),
//                        txtrid.getText(),
                        cmbrecep.getSelectedItem().toString(),
                        lbldate.getText(),
                        lbltime.getText(),
                        txtcustname.getText(),
                        txttp.getText(),
                        qty,
                        ststus
                );
                boolean addorder = ManageOrderController.updateCustomer(orderDTO);
                if (addorder) {
                    JOptionPane.showMessageDialog(this, "Qty has been Update Successfully");
                    loadAllCustomers();
//                clearText();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Update Qty");
                }
            } catch (Exception ex) {
                Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "You Can't Reduce Qty");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReceptionForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnplace_order;
    private javax.swing.JComboBox<String> cmbrecep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsqty;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTable tblorder;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtoid;
    private javax.swing.JTextField txttp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadAllCustomers();
    }
    
     private void loadAllReception(){
        try {
            cmbrecep.removeAll();
            List<OrderDTO> allRec=ManageChefController.getAllCustomers();
            for (OrderDTO orderDTO : allRec) {
                cmbrecep.addItem(orderDTO.getCustName());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ReceptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
